name: Test Repo Autobuild func

on:
  push:
    branches: [main]

jobs:
  gitclone:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pkg:         
          - brave-bin
          - yay
    steps:
     - name: Checkout Code
       uses: actions/checkout@v3
       
     - name: git clone
       run: git clone https://aur.archlinux.org/${{ matrix.pkg }}.git
        
     - name: Build Package
       uses: 2m/arch-pkgbuild-builder@v1.16
       with:
        target: 'pkgbuild'
        pkgname: '${{ matrix.pkg }}'
       
     - name: Move Packages  
       run: mkdir packages $$ mv *.zst /packages
     
     - name: Upload Package
       uses: actions/upload-artifact@v3
       with:
        name: test-${{ matrix.pkg }}
        path: packages/
        
